name: Production S3 Images Sync

on:
  workflow_call:
    inputs:
      sourceDir:
        description: >
          Source dir for images.
        required: true
        type: string
      destDir:
        description: >
          Destination dir for images.
        required: true
        type: string
    secrets:
      AWS_S3_BUCKET:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  build:
    name: Syncing Prod CDN
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089
      - uses: jakejarvis/s3-sync-action@7ed8b112447abb09f1da74f3466e4194fc7a6311
        with:
          args: --exclude "\*.webp" --size-only
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_S3_BUCKET }} # production bucket website.niche.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PRODUCTION_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PRODUCTION_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: ${{ inputs.sourceDir }}
          DEST_DIR: ${{ inputs.destDir }}
      - uses: jakejarvis/s3-sync-action@7ed8b112447abb09f1da74f3466e4194fc7a6311
        with:
          args: --exclude "\*" --include "\*.webp" --content-type image/webp --size-only
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_S3_BUCKET }} # production bucket website.niche.com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PRODUCTION_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PRODUCTION_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: ${{ inputs.sourceDir }}
          DEST_DIR: ${{ inputs.destDir }}
