name: Push Helm Charts
permissions:
  contents: write
  pull-requests: write
on:
  workflow_call:
    inputs:
      appchange:
        description: >
          Deprecated: This input is unused.

          'true' if APPVERSION in the version.env file changed, 'false' otherwise
        required: false
        type: string
      apps:
        description: >
          A JSON array containing the names of all apps the repo ships to stage.
          If present, this information will be written to the Helm chart release
          description.

          Example: '["service", "service-updater"]'
        required: false
        type: string
      appversion:
        description: >
          The current version of the app
        required: false # Required for push events
        type: string
      chartchange:
        description: >
          'true' if CHARTVERSION in the version.env file changed, 'false' otherwise
        required: false # Required for push events
        type: string
      chartversion:
        description: >
          The current version of the Helm chart(s)
        required: false # Required for push events
        type: string
      protect-dev:
        description: >
          Use a PR to update dev with new Helm chart versions
          instead of pushing directly
        required: false
        default: false
        type: boolean
      bypass-dev-protections:
        description: >
          Use custom user to override branch protections when
          pushing directly to dev
        required: false
        default: false
        type: boolean
      no-slack:
        description:
          Disables slack notifications
        required: false
        default: false
        type: boolean
      checkout-ref:
        description:
          Specify a branch, tag, or SHA to checkout documented
          at https://github.com/actions/checkout
        required: false
        default: ''
        type: string
    secrets:
      ECR_ACCESS_KEY_ID:
        required: true
      ECR_SECRET_ACCESS_KEY:
        required: true
      SLACK_BOT_TOKEN:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      PUSH_CHARTS_TOKEN:
        required: false

jobs:  
  # Builds and ships Helm charts if necessary
  push-charts:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' || 
      github.event_name == 'release'
    steps:
      - name: Validate required inputs for push events
        if: github.event_name == 'push'
        run: |
          appversion="${{ inputs.appversion }}"
          echo "appversion=$appversion"

          chartchange="${{ inputs.chartchange }}"
          echo "chartchange=$chartchange"

          chartversion="${{ inputs.chartversion }}"
          echo "chartversion=$chartversion"

          if [[ -z "$appversion" || -z "$chartchange" || -z "$chartversion" ]]; then
            echo "::error::appversion, chartchange, and chartversion are required for push events"
            exit 1
          fi

      # Checkout as github-actions for normal workflow
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        if: |
          !inputs.bypass-dev-protections
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ inputs.checkout-ref }}
      # Checkout as given token to bypass branch protections
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        if: |
          inputs.bypass-dev-protections
        with:
          token: ${{ secrets.PUSH_CHARTS_TOKEN }}
          ref: ${{ inputs.checkout-ref }}

      # If the chart version changed we need to reflect it in the chart(s).
      # Also reflects app changes if both change in the same PR.
      - name: Update Versions in Helm Chart(s)
        if: |
          (github.event_name == 'push' &&
           inputs.chartchange == 'true') ||
          (github.event_name == 'release' &&
           startsWith(github.ref_name, 'helm-chart'))
        run: |
          . version.env
          sed -i 's/^appVersion: .*/appVersion: \"'${APPVERSION}'\"/' charts/*/Chart.yaml
          sed -i 's/^version: .*/version: '${CHARTVERSION}'/' charts/*/Chart.yaml

      # If the chart version changed we need to reflect it in the chart(s).
      # Also reflects app changes if both change in the same PR.
      - name: Push Helm Chart Updates
        if: |
          github.event_name == 'push' &&
          inputs.chartchange == 'true' &&
          !inputs.protect-dev
        run: |
          . version.env
          if ! git diff --quiet; then
            git config --global user.name github-actions
            git config --global user.email ""
            git add -A
            git commit -m "[skip ci] Updating Helm charts with appversion ${APPVERSION}, chartversion ${CHARTVERSION}"
            git push
          fi

      # Updates Helm chart versions via PR
      - name: PR Helm Chart Updates
        id: create-pull-request
        if: |
          github.event_name == 'push' &&
          inputs.chartchange == 'true' &&
          inputs.protect-dev
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          base: dev
          branch: chart-version-update
          title: Updating Helm Chart Versions
          body: Updating Helm charts with appversion ${{ inputs.appversion }}, chartversion ${{ inputs.chartversion }}
          delete-branch: true
          commit-message: Helm charts appversion ${{ inputs.appversion }}, chartversion ${{ inputs.chartversion }}

      # If this was a push to dev and we need to ship charts, ship prereleases first
      - name: Mark as Prerelease
        id: mark-prerelease
        if: |
          github.event_name == 'push' &&
          inputs.chartchange == 'true'
        run: |
          sed -i '/^version/ s/$/-beta/' charts/*/Chart.yaml

      # AWS Setup
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        if: |
          (github.event_name == 'push' &&
           inputs.chartchange == 'true') ||
          (github.event_name == 'release' &&
           startsWith(github.ref_name, 'helm-chart'))
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Push charts to ECR for any qualifying push to dev
      # or any non-prerelease that starts with "helm-chart"
      - name: Helm Push
        if: |
          (github.event_name == 'push' &&
           inputs.chartchange == 'true') ||
          (github.event_name == 'release' &&
           startsWith(github.ref_name, 'helm-chart'))
        env:
          REGISTRY_URL: oci://${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
        run: |
          REGISTRY=$(echo "${REGISTRY_URL}" | awk -F[/:] '{print $4}') # Get registry host from url
          aws ecr get-login-password | helm registry login -u AWS --password-stdin ${REGISTRY}
          for chart in charts/*; do
            echo "Packaging chart '$chart'"
            PKG_RESPONSE=$(helm package "$chart")
            echo "$PKG_RESPONSE"
            CHART_TAR_GZ=$(basename "$PKG_RESPONSE")
            echo "Pushing chart $CHART_TAR_GZ to '$REGISTRY_URL'"
            helm push "$CHART_TAR_GZ" "$REGISTRY_URL"
            echo "Successfully pushed chart $CHART_TAR_GZ to '$REGISTRY_URL'"
          done

      - name: Get PR Metadata
        uses: nicheinc/get-pr-metadata@DELTA-3834-add-pr-labels-output
        id: get-pr
        if: |
          github.event_name == 'push' &&
          inputs.chartchange == 'true'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Cut a prerelease for the helm chart if it was a push
      - name: Create Prerelease for Helm Charts
        id: create-helm-prerelease
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        if: |
          github.event_name == 'push' &&
          inputs.chartchange == 'true'
        with:
          tag: "helm-chart-${{ inputs.chartversion }}"
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            <!-- The following metadata will be parsed by automation - do not modify! -->

            appversion ${{ inputs.appversion }}

            ${{ steps.get-pr.outputs.pr_found == 'true'
              && format('[PR #{0}]({1})', steps.get-pr.outputs.pr_number, steps.get-pr.outputs.pr_url)
              || 'This release is not associated with any pull request.'
            }}

            ${{ inputs.apps
              && format('Apps: {0}', join(fromJson(inputs.apps), ', '))
            }}

      # Notify in Slack
      - name: Post Helm Chart Prerelease to Slack
        if: |
          github.event_name == 'push' && 
          inputs.chartchange == 'true' &&
          !inputs.no-slack
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: "C2C5JV162"
            text: "GitHub has built `${{ github.event.repository.name }}:helm-chart-${{ inputs.chartversion }}` for <${{ steps.create-helm-prerelease.outputs.html_url }}|release>. :shipitparrot:"

      - name: Post Helm Chart Release to Slack
        if: |
          github.event_name == 'release' &&
          startsWith(github.ref_name, 'helm-chart') &&
          !inputs.no-slack
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: "C2C5JV162"
            text: "GitHub has promoted `${{ github.event.repository.name }}:${{ github.ref_name }}` to production. :shipitparrot:"
